In [4]:
import numpy as np

u = np.arange(10).reshape(5, 2)
print(u)
a = np.array([1, 0, 0, 1, 0])
r, _ = u.shape  # get how many rows to use in np.arange(r)
print(np.arange(r))

print(u[np.arange(r), a])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4]
[1 2 4 7 8]
